### ISSUE TITLE
Support change listeners on server

### ISSUE THREAD

**Issue by 3mcd** [colyseus/schema#36]
Versions:

- colyseus@0.11.0
- @colyseus/schema@0.4.53

I'm experimenting with ways to synchronize simulation state of a physics library with a Schema tree. I want to subscribe to changes in Schema so I can apply them to the simulation. When change listeners are set (`onAdd`, `onChange`, etc.) on a `MapSchema`, I get the following error:

```
Error: a 'BodyState' was expected, but 'Function' was provided in PhysicsState#bodies
    at new EncodeSchemaError (/app/node_modules/@colyseus/schema/lib/Schema.js:25:42)
    at assertInstanceType (/app/node_modules/@colyseus/schema/lib/Schema.js:64:15)
    at _loop_2 (/app/node_modules/@colyseus/schema/lib/Schema.js:542:25)
    at PhysicsState.Schema.encode (/app/node_modules/@colyseus/schema/lib/Schema.js:578:13)
    at _loop_2 (/app/node_modules/@colyseus/schema/lib/Schema.js:439:48)
    at SystemState.Schema.encode (/app/node_modules/@colyseus/schema/lib/Schema.js:578:13)
    at SchemaSerializer.applyPatches (/app/node_modules/colyseus/lib/serializer/SchemaSerializer.js:28:44)
    at MainRoom.broadcastPatch (/app/node_modules/colyseus/lib/Room.js:206:33)
    at Timeout._onTimeout (/app/node_modules/colyseus/lib/Room.js:93:22)
    at listOnTimeout (internal/timers.js:531:17)
```

I think this behavior is currently expected since these callbacks are listed under the [Client-side](https://docs.colyseus.io/state/schema/#client-side) heading in the Colyseus docs.

**Comment by endel** [comment]
Hi @3mcd, the schema callbacks occur during decoding time, I'm afraid this won't be possible as the server only encodes the values. 

The server encodes based on the `.$changes` property of each child structure in the state. You may be able to get them using it, but the API wasn't planned for such.

**Comment by 3mcd** [comment]
Makes sense. I started down that path and it's working well. Thanks for the tip.

**Comment by udamir** [comment]
@3mcd, hi! Have you find the way how to subscribe on state changes on server side?

**Comment by 3mcd** [comment]
Hello @udamir! I ended up using the `$changes` API that @endel mentioned above:

https://github.com/local-group-games/warbird/blob/master/packages/ecs/src/World.ts#L132
