### ISSUE TITLE
Possible bug related to deep cloning on Schema

### ISSUE THREAD

**Issue by virtumonde** [colyseus/schema#81]
There is a very high chance that there is a bug related to deep cloning on Schemas.

```
export default class Humanoid extends Schema {
    constructor(that : any, sessionId : string, dungeonId : string, x : number, y : number) {
        super()
        this.sessionId = sessionId;
        this.dungeonId = dungeonId;
        this.health = 100;
        this.x = x;
        this.y = y;
        this.pX = x;
        this.pY = y;
        this.dX = x;
        this.dY = y;
        this.isOnCooldown = false;
        this.isAttacking = false;
        this.isMoving = true;
        this.that = that;

        let inventory = new ArraySchema < Item > ();
        for (let i = 0; i < 60; i++) {
            let item = new Item(nothing.NOTHING);
            inventory.push(item);
        }
        this.inventory = inventory;
    }
}
```
```
export default class Item extends Schema {
    constructor(data: any) {
        super();
        this.name = data.name;
    }

    @type('string')
    name: string;
}
```
If Humanoid is cloned, I get this error:
```
TypeError: Cannot read property 'name' of undefined
    at new Item (/Users/virtumonde/Desktop/development/web-dungeon/overworld-server/src/website/classes/Dungeon/Humanoid/Item.ts:6:26)
    at Item.Schema.clone (/Users/virtumonde/Desktop/development/web-dungeon/overworld-server/node_modules/@colyseus/schema/src/Schema.ts:686:24)
    at /Users/virtumonde/Desktop/development/web-dungeon/overworld-server/node_modules/@colyseus/schema/src/types/ArraySchema.ts:62:64
    at Array.map (<anonymous>)
    at Proxy.value (/Users/virtumonde/Desktop/development/web-dungeon/overworld-server/node_modules/@colyseus/schema/src/types/ArraySchema.ts:60:58)
    at Player.Schema.clone (/Users/virtumonde/Desktop/development/web-dungeon/overworld-server/node_modules/@colyseus/schema/src/Schema.ts:694:45)
    at Object.exports.default (/Users/virtumonde/Desktop/development/web-dungeon/overworld-server/src/website/processors/CHANGE_DUNGEON.ts:85:101)
    at Object.CHANGE_DUNGEON (/Users/virtumonde/Desktop/development/web-dungeon/overworld-server/src/website/index.ts:79:27)
    at Website._onMessage (/Users/virtumonde/Desktop/development/web-dungeon/overworld-server/node_modules/colyseus/lib/Room.js:443:52)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.EventEmitter.emit (domain.js:485:12)
    at Receiver.receiverOnMessage (/Users/virtumonde/Desktop/development/web-dungeon/overworld-server/node_modules/colyseus/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.EventEmitter.emit (domain.js:485:12)
    at Receiver.dataMessage (/Users/virtumonde/Desktop/development/web-dungeon/overworld-server/node_modules/colyseus/node_modules/ws/lib/receiver.js:427:14)
    at Receiver.getData (/Users/virtumonde/Desktop/development/web-dungeon/overworld-server/node_modules/colyseus/node_modules/ws/lib/receiver.js:366:17)
```

**Comment by endel** [comment]
Hi @virtumonde,

As the `.clone()` method needs to instantiate the object internally, it does not know about your particular constructor arguments.

As most people seem to be using the constructor to pass initial data, I'm going to include an `.assign()` method on the next version: https://github.com/colyseus/schema/blob/0.6.0/src/Schema.ts#L150-L158

```typescript
    public assign(
        props: { [prop in NonFunctionPropNames<this>]: this[prop] }
    ) {
        Object.assign(this, props);
        return this;
    }
```

As a workaround, for now, I'd suggest using any constructor arguments as optional for the `Schema` structures. In the future, it is going to be recommended to use either `new Item({name: "Item name"})` or `new Item().assign({name: "Item name"})`

**Comment by virtumonde** [comment]
Best support as always. Thank you @endel.
