### ISSUE TITLE
TypeError: Cannot read property 'schema' of undefined on 0.14.0-alpha.2

### ISSUE THREAD

**Issue by virtumonde** [colyseus/schema#83]
I am getting this following error related to filters even though I am not using them:
```
TypeError: Cannot read property 'schema' of undefined
    at Object.hasFilter (/Users/virtumonde/Desktop/dev/overworld-earth/overworld-earth-server/node_modules/colyseus/node_modules/@colyseus/schema/src/annotations.ts:127:31)
    at SchemaSerializer.reset (/Users/virtumonde/Desktop/dev/overworld-earth/overworld-earth-server/node_modules/colyseus/lib/serializer/SchemaSerializer.js:15:36)
    at OverworldRoom.setState (/Users/virtumonde/Desktop/dev/overworld-earth/overworld-earth-server/node_modules/colyseus/lib/Room.js:138:26)
    at OverworldRoom.onCreate (/Users/virtumonde/Desktop/dev/overworld-earth/overworld-earth-server/OverworldRoom.ts:13:10)
    at /Users/virtumonde/Desktop/dev/overworld-earth/overworld-earth-server/node_modules/colyseus/lib/MatchMaker.js:224:28
    at Generator.next (<anonymous>)
    at /Users/virtumonde/Desktop/dev/overworld-earth/overworld-earth-server/node_modules/colyseus/lib/MatchMaker.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/virtumonde/Desktop/dev/overworld-earth/overworld-earth-server/node_modules/colyseus/lib/MatchMaker.js:4:12)
    at handleCreateRoom (/Users/virtumonde/Desktop/dev/overworld-earth/overworld-earth-server/node_modules/colyseus/lib/MatchMaker.js:210:12)
```

**Comment by endel** [comment]
Thanks for testing this early and reporting back @virtumonde! Gonna check this right now.

**Comment by virtumonde** [comment]
@endel Is it? Also, I am getting this in my client React Native (same version, 0.14.0-alpha.2):
```
JOIN ERROR [Error: Cannot read property 'schema' of undefined]
```

**Comment by endel** [comment]
That's likely a mistake I'm making trying to identify if the schema structures have `@filter()` defined on them or not. Sorry for the inconvenience 😅

**Comment by endel** [comment]
I've just published `@colyseus/schema@1.0.0-alpha.9` with another approach detecting filters (https://github.com/colyseus/schema/commit/d8e6cc2cce986ecee38d94689c22f95b5cb65e69). 
Do you mind installing this version in the server to check if this issue is gone @virtumonde?

**Comment by virtumonde** [comment]
@endel, it seems I pulled the trigger too soon. It's my mistake :sweat_smile: I am using **0.5.40** instead of **1.0.0-alpha.7**. Everything works if I use the new version. I see you're not losing tempo, still one of the fastest maintainers I have ever seen.:fire:

**Comment by virtumonde** [comment]
@endel, I'll test it just in case.

**Comment by endel** [comment]
Thanks! So the previous filter detection was working for you then? 😅

**Comment by virtumonde** [comment]
> Thanks! So the previous filter detection was working for you then? 😅

I haven't used filters at all but I am planning to. I am using this version because I get a strange error in iOS if I use the old version.

**Comment by endel** [comment]
Oh, be careful! The alpha version mentioned on #74 is `0.13.2-alpha.0`, with the previous Schema implementation. The version `0.14.0-alpha.2` is using the new `@colyseus/schema` implementation, which is going to introduce a few breaking changes: https://deploy-preview-45--colyseus-docs.netlify.app/migrating/0.14/

The version 0.14 is **kinda** ready, I'm still double-checking a couple of things before announcing it
